// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countCommentsByAuthor = `-- name: CountCommentsByAuthor :one
SELECT COUNT(*) FROM comments WHERE author_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCommentsByAuthor(ctx context.Context, authorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsByAuthor, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCommentsInRange = `-- name: CountCommentsInRange :one
SELECT COUNT(*) FROM comments
WHERE created_at >= $1 AND created_at < $2 AND deleted_at IS NULL
`

type CountCommentsInRangeParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) CountCommentsInRange(ctx context.Context, arg CountCommentsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommentsInRange, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTopLevelComments = `-- name: CountTopLevelComments :one
SELECT COUNT(*) FROM comments
WHERE post_id = $1 AND parent_id IS NULL AND deleted_at IS NULL
`

func (q *Queries) CountTopLevelComments(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTopLevelComments, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (content, author_id, post_id, parent_id)
VALUES ($1, $2, $3, $4)
RETURNING id, content, author_id, post_id, parent_id, pinned_at, deleted_at, created_at, updated_at
`

type CreateCommentParams struct {
	Content  string        `json:"content"`
	AuthorID uuid.UUID     `json:"author_id"`
	PostID   uuid.UUID     `json:"post_id"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.Content,
		arg.AuthorID,
		arg.PostID,
		arg.ParentID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorID,
		&i.PostID,
		&i.ParentID,
		&i.PinnedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, content, author_id, post_id, parent_id, pinned_at, deleted_at, created_at, updated_at FROM comments WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorID,
		&i.PostID,
		&i.ParentID,
		&i.PinnedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentByIDIncludeDeleted = `-- name: GetCommentByIDIncludeDeleted :one
SELECT id, content, author_id, post_id, parent_id, pinned_at, deleted_at, created_at, updated_at FROM comments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCommentByIDIncludeDeleted(ctx context.Context, id uuid.UUID) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByIDIncludeDeleted, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorID,
		&i.PostID,
		&i.ParentID,
		&i.PinnedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCommentsByAuthor = `-- name: ListCommentsByAuthor :many
SELECT id, content, author_id, post_id, parent_id, pinned_at, deleted_at, created_at, updated_at FROM comments
WHERE author_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByAuthorParams struct {
	AuthorID uuid.UUID `json:"author_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListCommentsByAuthor(ctx context.Context, arg ListCommentsByAuthorParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorID,
			&i.PostID,
			&i.ParentID,
			&i.PinnedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT id, content, author_id, post_id, parent_id, pinned_at, deleted_at, created_at, updated_at FROM comments
WHERE parent_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListRepliesParams struct {
	ParentID uuid.NullUUID `json:"parent_id"`
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
}

func (q *Queries) ListReplies(ctx context.Context, arg ListRepliesParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listReplies, arg.ParentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorID,
			&i.PostID,
			&i.ParentID,
			&i.PinnedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevelComments = `-- name: ListTopLevelComments :many
SELECT id, content, author_id, post_id, parent_id, pinned_at, deleted_at, created_at, updated_at FROM comments
WHERE post_id = $1 AND parent_id IS NULL AND deleted_at IS NULL
ORDER BY pinned_at DESC NULLS LAST, created_at ASC
LIMIT $2 OFFSET $3
`

type ListTopLevelCommentsParams struct {
	PostID uuid.UUID `json:"post_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListTopLevelComments(ctx context.Context, arg ListTopLevelCommentsParams) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listTopLevelComments, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Comment{}
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.AuthorID,
			&i.PostID,
			&i.ParentID,
			&i.PinnedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinComment = `-- name: PinComment :exec
UPDATE comments SET pinned_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) PinComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, pinComment, id)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteComment, id)
	return err
}

const unpinComment = `-- name: UnpinComment :exec
UPDATE comments SET pinned_at = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UnpinComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unpinComment, id)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, content, author_id, post_id, parent_id, pinned_at, deleted_at, created_at, updated_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.AuthorID,
		&i.PostID,
		&i.ParentID,
		&i.PinnedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
