// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package db

import (
	"context"
)

const getConfigValue = `-- name: GetConfigValue :one
SELECT value FROM site_config WHERE key = $1 LIMIT 1
`

func (q *Queries) GetConfigValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfigValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listConfig = `-- name: ListConfig :many
SELECT key, value, updated_at FROM site_config ORDER BY key
`

func (q *Queries) ListConfig(ctx context.Context) ([]SiteConfig, error) {
	rows, err := q.db.QueryContext(ctx, listConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteConfig{}
	for rows.Next() {
		var i SiteConfig
		if err := rows.Scan(&i.Key, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfigValue = `-- name: UpsertConfigValue :exec
INSERT INTO site_config (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type UpsertConfigValueParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertConfigValue(ctx context.Context, arg UpsertConfigValueParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfigValue, arg.Key, arg.Value)
	return err
}
