// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"
)

const decrementImageRefCount = `-- name: DecrementImageRefCount :exec
UPDATE images SET ref_count = ref_count - 1 WHERE url = $1
`

func (q *Queries) DecrementImageRefCount(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, decrementImageRefCount, url)
	return err
}

const getImageByURL = `-- name: GetImageByURL :one
SELECT id, url, ref_count, created_at FROM images WHERE url = $1 LIMIT 1
`

func (q *Queries) GetImageByURL(ctx context.Context, url string) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByURL, url)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.RefCount,
		&i.CreatedAt,
	)
	return i, err
}

const upsertImage = `-- name: UpsertImage :one
INSERT INTO images (url)
VALUES ($1)
ON CONFLICT (url) DO UPDATE SET ref_count = images.ref_count + 1
RETURNING id, url, ref_count, created_at
`

func (q *Queries) UpsertImage(ctx context.Context, url string) (Image, error) {
	row := q.db.QueryRowContext(ctx, upsertImage, url)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.RefCount,
		&i.CreatedAt,
	)
	return i, err
}
