// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO message_participants (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addParticipant, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO message_conversations DEFAULT VALUES
RETURNING id, last_message_at, created_at
`

func (q *Queries) CreateConversation(ctx context.Context) (MessageConversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation)
	var i MessageConversation
	err := row.Scan(&i.ID, &i.LastMessageAt, &i.CreatedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, content, reply_to_id)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_id, content, reply_to_id, deleted_at, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID     `json:"conversation_id"`
	SenderID       uuid.UUID     `json:"sender_id"`
	Content        string        `json:"content"`
	ReplyToID      uuid.NullUUID `json:"reply_to_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Content,
		arg.ReplyToID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.ReplyToID,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getConversationBetweenUsers = `-- name: GetConversationBetweenUsers :one
SELECT mc.id, mc.last_message_at, mc.created_at FROM message_conversations mc
JOIN message_participants mp1 ON mp1.conversation_id = mc.id AND mp1.user_id = $1
JOIN message_participants mp2 ON mp2.conversation_id = mc.id AND mp2.user_id = $2
LIMIT 1
`

type GetConversationBetweenUsersParams struct {
	UserID   uuid.UUID `json:"user_id"`
	UserID_2 uuid.UUID `json:"user_id_2"`
}

func (q *Queries) GetConversationBetweenUsers(ctx context.Context, arg GetConversationBetweenUsersParams) (MessageConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationBetweenUsers, arg.UserID, arg.UserID_2)
	var i MessageConversation
	err := row.Scan(&i.ID, &i.LastMessageAt, &i.CreatedAt)
	return i, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, last_message_at, created_at FROM message_conversations WHERE id = $1 LIMIT 1
`

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (MessageConversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, id)
	var i MessageConversation
	err := row.Scan(&i.ID, &i.LastMessageAt, &i.CreatedAt)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, conversation_id, sender_id, content, reply_to_id, deleted_at, created_at FROM messages WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.ReplyToID,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOtherParticipantUserID = `-- name: GetOtherParticipantUserID :one
SELECT user_id FROM message_participants
WHERE conversation_id = $1 AND user_id != $2
LIMIT 1
`

type GetOtherParticipantUserIDParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOtherParticipantUserID(ctx context.Context, arg GetOtherParticipantUserIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getOtherParticipantUserID, arg.ConversationID, arg.UserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT conversation_id, user_id, unread_count, last_read_at FROM message_participants WHERE conversation_id = $1 AND user_id = $2 LIMIT 1
`

type GetParticipantParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (MessageParticipant, error) {
	row := q.db.QueryRowContext(ctx, getParticipant, arg.ConversationID, arg.UserID)
	var i MessageParticipant
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.UnreadCount,
		&i.LastReadAt,
	)
	return i, err
}

const getParticipants = `-- name: GetParticipants :many
SELECT conversation_id, user_id, unread_count, last_read_at FROM message_participants WHERE conversation_id = $1
`

func (q *Queries) GetParticipants(ctx context.Context, conversationID uuid.UUID) ([]MessageParticipant, error) {
	rows, err := q.db.QueryContext(ctx, getParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageParticipant{}
	for rows.Next() {
		var i MessageParticipant
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.UnreadCount,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalUnreadCount = `-- name: GetTotalUnreadCount :one
SELECT COALESCE(SUM(unread_count), 0)::BIGINT FROM message_participants WHERE user_id = $1
`

func (q *Queries) GetTotalUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalUnreadCount, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const incrementUnreadCounts = `-- name: IncrementUnreadCounts :exec
UPDATE message_participants
SET unread_count = unread_count + 1
WHERE conversation_id = $1 AND user_id != $2
`

type IncrementUnreadCountsParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) IncrementUnreadCounts(ctx context.Context, arg IncrementUnreadCountsParams) error {
	_, err := q.db.ExecContext(ctx, incrementUnreadCounts, arg.ConversationID, arg.UserID)
	return err
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT mc.id, mc.last_message_at, mc.created_at FROM message_conversations mc
JOIN message_participants mp ON mp.conversation_id = mc.id
WHERE mp.user_id = $1
ORDER BY mc.last_message_at DESC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListConversationsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]MessageConversation, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageConversation{}
	for rows.Next() {
		var i MessageConversation
		if err := rows.Scan(&i.ID, &i.LastMessageAt, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, sender_id, content, reply_to_id, deleted_at, created_at FROM messages
WHERE conversation_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.ReplyToID,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE message_participants
SET unread_count = 0, last_read_at = NOW()
WHERE conversation_id = $1 AND user_id = $2
`

type MarkConversationReadParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.ExecContext(ctx, markConversationRead, arg.ConversationID, arg.UserID)
	return err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteMessage, id)
	return err
}

const updateConversationLastMessage = `-- name: UpdateConversationLastMessage :exec
UPDATE message_conversations SET last_message_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateConversationLastMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateConversationLastMessage, id)
	return err
}
