// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type UserRole string

const (
	UserRoleUSER  UserRole = "USER"
	UserRoleADMIN UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Comment struct {
	ID        uuid.UUID     `json:"id"`
	Content   string        `json:"content"`
	AuthorID  uuid.UUID     `json:"author_id"`
	PostID    uuid.UUID     `json:"post_id"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	PinnedAt  sql.NullTime  `json:"pinned_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type EmailPreference struct {
	UserID  uuid.UUID `json:"user_id"`
	Type    string    `json:"type"`
	Enabled bool      `json:"enabled"`
}

type Image struct {
	ID        uuid.UUID `json:"id"`
	Url       string    `json:"url"`
	RefCount  int32     `json:"ref_count"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID     `json:"id"`
	ConversationID uuid.UUID     `json:"conversation_id"`
	SenderID       uuid.UUID     `json:"sender_id"`
	Content        string        `json:"content"`
	ReplyToID      uuid.NullUUID `json:"reply_to_id"`
	DeletedAt      sql.NullTime  `json:"deleted_at"`
	CreatedAt      time.Time     `json:"created_at"`
}

type MessageConversation struct {
	ID            uuid.UUID    `json:"id"`
	LastMessageAt sql.NullTime `json:"last_message_at"`
	CreatedAt     time.Time    `json:"created_at"`
}

type MessageParticipant struct {
	ConversationID uuid.UUID    `json:"conversation_id"`
	UserID         uuid.UUID    `json:"user_id"`
	UnreadCount    int32        `json:"unread_count"`
	LastReadAt     sql.NullTime `json:"last_read_at"`
}

type Notification struct {
	ID         uuid.UUID      `json:"id"`
	Type       string         `json:"type"`
	UserID     uuid.UUID      `json:"user_id"`
	FromUserID uuid.NullUUID  `json:"from_user_id"`
	PostID     uuid.NullUUID  `json:"post_id"`
	CommentID  uuid.NullUUID  `json:"comment_id"`
	Content    sql.NullString `json:"content"`
	Read       bool           `json:"read"`
	CreatedAt  time.Time      `json:"created_at"`
}

type NotificationPreference struct {
	UserID       uuid.UUID `json:"user_id"`
	Type         string    `json:"type"`
	InAppEnabled bool      `json:"in_app_enabled"`
	PushEnabled  bool      `json:"push_enabled"`
}

type OauthAccount struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Post struct {
	ID           uuid.UUID    `json:"id"`
	Title        string       `json:"title"`
	Content      string       `json:"content"`
	AuthorID     uuid.UUID    `json:"author_id"`
	Views        int32        `json:"views"`
	Closed       bool         `json:"closed"`
	PinnedAt     sql.NullTime `json:"pinned_at"`
	CommentCount int32        `json:"comment_count"`
	LastReplyAt  sql.NullTime `json:"last_reply_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	CreatedAt    time.Time    `json:"created_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type PostRead struct {
	PostID    uuid.UUID `json:"post_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PostSubscription struct {
	PostID    uuid.UUID `json:"post_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type PushSubscription struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Endpoint  string    `json:"endpoint"`
	P256dh    string    `json:"p256dh"`
	Auth      string    `json:"auth"`
	CreatedAt time.Time `json:"created_at"`
}

type SiteConfig struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Verified     bool           `json:"verified"`
	Avatar       sql.NullString `json:"avatar"`
	Introduction sql.NullString `json:"introduction"`
	Role         UserRole       `json:"role"`
	Banned       bool           `json:"banned"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type UserSubscription struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type UserVisit struct {
	VisitDate time.Time `json:"visit_date"`
	UserID    uuid.UUID `json:"user_id"`
}

type VerificationCode struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	Type      string    `json:"type"`
	ExpiresAt time.Time `json:"expires_at"`
	Used      bool      `json:"used"`
	CreatedAt time.Time `json:"created_at"`
}
