// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (type, user_id, from_user_id, post_id, comment_id, content)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, type, user_id, from_user_id, post_id, comment_id, content, read, created_at
`

type CreateNotificationParams struct {
	Type       string         `json:"type"`
	UserID     uuid.UUID      `json:"user_id"`
	FromUserID uuid.NullUUID  `json:"from_user_id"`
	PostID     uuid.NullUUID  `json:"post_id"`
	CommentID  uuid.NullUUID  `json:"comment_id"`
	Content    sql.NullString `json:"content"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.Type,
		arg.UserID,
		arg.FromUserID,
		arg.PostID,
		arg.CommentID,
		arg.Content,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.UserID,
		&i.FromUserID,
		&i.PostID,
		&i.CommentID,
		&i.Content,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailPref = `-- name: GetEmailPref :one
SELECT user_id, type, enabled FROM email_preferences WHERE user_id = $1 AND type = $2 LIMIT 1
`

type GetEmailPrefParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
}

func (q *Queries) GetEmailPref(ctx context.Context, arg GetEmailPrefParams) (EmailPreference, error) {
	row := q.db.QueryRowContext(ctx, getEmailPref, arg.UserID, arg.Type)
	var i EmailPreference
	err := row.Scan(&i.UserID, &i.Type, &i.Enabled)
	return i, err
}

const getEmailPreferences = `-- name: GetEmailPreferences :many
SELECT user_id, type, enabled FROM email_preferences WHERE user_id = $1
`

func (q *Queries) GetEmailPreferences(ctx context.Context, userID uuid.UUID) ([]EmailPreference, error) {
	rows, err := q.db.QueryContext(ctx, getEmailPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailPreference{}
	for rows.Next() {
		var i EmailPreference
		if err := rows.Scan(&i.UserID, &i.Type, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, type, user_id, from_user_id, post_id, comment_id, content, read, created_at FROM notifications WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.UserID,
		&i.FromUserID,
		&i.PostID,
		&i.CommentID,
		&i.Content,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationPref = `-- name: GetNotificationPref :one
SELECT user_id, type, in_app_enabled, push_enabled FROM notification_preferences WHERE user_id = $1 AND type = $2 LIMIT 1
`

type GetNotificationPrefParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
}

func (q *Queries) GetNotificationPref(ctx context.Context, arg GetNotificationPrefParams) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPref, arg.UserID, arg.Type)
	var i NotificationPreference
	err := row.Scan(
		&i.UserID,
		&i.Type,
		&i.InAppEnabled,
		&i.PushEnabled,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :many
SELECT user_id, type, in_app_enabled, push_enabled FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.QueryContext(ctx, getNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.UserID,
			&i.Type,
			&i.InAppEnabled,
			&i.PushEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, type, user_id, from_user_id, post_id, comment_id, content, read, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.UserID,
			&i.FromUserID,
			&i.PostID,
			&i.CommentID,
			&i.Content,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationReadByID = `-- name: MarkNotificationReadByID :exec
UPDATE notifications SET read = TRUE WHERE id = $1
`

func (q *Queries) MarkNotificationReadByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markNotificationReadByID, id)
	return err
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET read = TRUE WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) MarkNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markNotificationsRead, userID)
	return err
}

const upsertEmailPreference = `-- name: UpsertEmailPreference :exec
INSERT INTO email_preferences (user_id, type, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, type) DO UPDATE
SET enabled = EXCLUDED.enabled
`

type UpsertEmailPreferenceParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Type    string    `json:"type"`
	Enabled bool      `json:"enabled"`
}

func (q *Queries) UpsertEmailPreference(ctx context.Context, arg UpsertEmailPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmailPreference, arg.UserID, arg.Type, arg.Enabled)
	return err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :exec
INSERT INTO notification_preferences (user_id, type, in_app_enabled, push_enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, type) DO UPDATE
SET in_app_enabled = EXCLUDED.in_app_enabled,
    push_enabled   = EXCLUDED.push_enabled
`

type UpsertNotificationPreferenceParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Type         string    `json:"type"`
	InAppEnabled bool      `json:"in_app_enabled"`
	PushEnabled  bool      `json:"push_enabled"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.Type,
		arg.InAppEnabled,
		arg.PushEnabled,
	)
	return err
}
