// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM posts WHERE deleted_at IS NULL
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsByAuthor = `-- name: CountPostsByAuthor :one
SELECT COUNT(*) FROM posts WHERE author_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountPostsByAuthor(ctx context.Context, authorID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsByAuthor, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPostsInRange = `-- name: CountPostsInRange :one
SELECT COUNT(*) FROM posts
WHERE created_at >= $1 AND created_at < $2 AND deleted_at IS NULL
`

type CountPostsInRangeParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) CountPostsInRange(ctx context.Context, arg CountPostsInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPostsInRange, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, content, author_id)
VALUES ($1, $2, $3)
RETURNING id, title, content, author_id, views, closed, pinned_at, comment_count, last_reply_at, deleted_at, created_at, updated_at
`

type CreatePostParams struct {
	Title    string    `json:"title"`
	Content  string    `json:"content"`
	AuthorID uuid.UUID `json:"author_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.Title, arg.Content, arg.AuthorID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.Views,
		&i.Closed,
		&i.PinnedAt,
		&i.CommentCount,
		&i.LastReplyAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decrementPostCommentCount = `-- name: DecrementPostCommentCount :exec
UPDATE posts
SET comment_count = GREATEST(comment_count - 1, 0),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DecrementPostCommentCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementPostCommentCount, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, title, content, author_id, views, closed, pinned_at, comment_count, last_reply_at, deleted_at, created_at, updated_at FROM posts WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.Views,
		&i.Closed,
		&i.PinnedAt,
		&i.CommentCount,
		&i.LastReplyAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostByIDIncludeDeleted = `-- name: GetPostByIDIncludeDeleted :one
SELECT id, title, content, author_id, views, closed, pinned_at, comment_count, last_reply_at, deleted_at, created_at, updated_at FROM posts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostByIDIncludeDeleted(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByIDIncludeDeleted, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.Views,
		&i.Closed,
		&i.PinnedAt,
		&i.CommentCount,
		&i.LastReplyAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasUserReadPost = `-- name: HasUserReadPost :one
SELECT EXISTS(
    SELECT 1 FROM post_reads WHERE post_id = $1 AND user_id = $2
)
`

type HasUserReadPostParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) HasUserReadPost(ctx context.Context, arg HasUserReadPostParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUserReadPost, arg.PostID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementPostCommentCount = `-- name: IncrementPostCommentCount :exec
UPDATE posts
SET comment_count = comment_count + 1,
    last_reply_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementPostCommentCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementPostCommentCount, id)
	return err
}

const incrementPostViews = `-- name: IncrementPostViews :exec
UPDATE posts SET views = views + 1 WHERE id = $1
`

func (q *Queries) IncrementPostViews(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementPostViews, id)
	return err
}

const listFeaturedPosts = `-- name: ListFeaturedPosts :many
SELECT id, title, content, author_id, views, closed, pinned_at, comment_count, last_reply_at, deleted_at, created_at, updated_at FROM posts
WHERE deleted_at IS NULL AND pinned_at IS NOT NULL
ORDER BY pinned_at DESC
LIMIT $1 OFFSET $2
`

type ListFeaturedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFeaturedPosts(ctx context.Context, arg ListFeaturedPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listFeaturedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.AuthorID,
			&i.Views,
			&i.Closed,
			&i.PinnedAt,
			&i.CommentCount,
			&i.LastReplyAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, content, author_id, views, closed, pinned_at, comment_count, last_reply_at, deleted_at, created_at, updated_at FROM posts
WHERE deleted_at IS NULL
ORDER BY pinned_at DESC NULLS LAST, created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.AuthorID,
			&i.Views,
			&i.Closed,
			&i.PinnedAt,
			&i.CommentCount,
			&i.LastReplyAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT id, title, content, author_id, views, closed, pinned_at, comment_count, last_reply_at, deleted_at, created_at, updated_at FROM posts
WHERE author_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPostsByAuthorParams struct {
	AuthorID uuid.UUID `json:"author_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.AuthorID,
			&i.Views,
			&i.Closed,
			&i.PinnedAt,
			&i.CommentCount,
			&i.LastReplyAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPosts = `-- name: ListRecentPosts :many
SELECT id, title, content, author_id, views, closed, pinned_at, comment_count, last_reply_at, deleted_at, created_at, updated_at FROM posts
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentPosts(ctx context.Context, arg ListRecentPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.AuthorID,
			&i.Views,
			&i.Closed,
			&i.PinnedAt,
			&i.CommentCount,
			&i.LastReplyAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinPost = `-- name: PinPost :exec
UPDATE posts SET pinned_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) PinPost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, pinPost, id)
	return err
}

const recordPostRead = `-- name: RecordPostRead :exec
INSERT INTO post_reads (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type RecordPostReadParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RecordPostRead(ctx context.Context, arg RecordPostReadParams) error {
	_, err := q.db.ExecContext(ctx, recordPostRead, arg.PostID, arg.UserID)
	return err
}

const setPostClosed = `-- name: SetPostClosed :exec
UPDATE posts SET closed = $2, updated_at = NOW() WHERE id = $1
`

type SetPostClosedParams struct {
	ID     uuid.UUID `json:"id"`
	Closed bool      `json:"closed"`
}

func (q *Queries) SetPostClosed(ctx context.Context, arg SetPostClosedParams) error {
	_, err := q.db.ExecContext(ctx, setPostClosed, arg.ID, arg.Closed)
	return err
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeletePost, id)
	return err
}

const unpinPost = `-- name: UnpinPost :exec
UPDATE posts SET pinned_at = NULL, updated_at = NOW() WHERE id = $1
`

func (q *Queries) UnpinPost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unpinPost, id)
	return err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts
SET title      = COALESCE($2, title),
    content    = COALESCE($3, content),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, title, content, author_id, views, closed, pinned_at, comment_count, last_reply_at, deleted_at, created_at, updated_at
`

type UpdatePostParams struct {
	ID      uuid.UUID      `json:"id"`
	Title   sql.NullString `json:"title"`
	Content sql.NullString `json:"content"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost, arg.ID, arg.Title, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.AuthorID,
		&i.Views,
		&i.Closed,
		&i.PinnedAt,
		&i.CommentCount,
		&i.LastReplyAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
