// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPushSubscription = `-- name: CreatePushSubscription :one
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (endpoint) DO UPDATE
SET p256dh = EXCLUDED.p256dh, auth = EXCLUDED.auth
RETURNING id, user_id, endpoint, p256dh, auth, created_at
`

type CreatePushSubscriptionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Endpoint string    `json:"endpoint"`
	P256dh   string    `json:"p256dh"`
	Auth     string    `json:"auth"`
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, createPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.CreatedAt,
	)
	return i, err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.ExecContext(ctx, deletePushSubscriptionByEndpoint, endpoint)
	return err
}

const getPushSubscriptionsByUserID = `-- name: GetPushSubscriptionsByUserID :many
SELECT id, user_id, endpoint, p256dh, auth, created_at FROM push_subscriptions WHERE user_id = $1
`

func (q *Queries) GetPushSubscriptionsByUserID(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getPushSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
