// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddParticipant(ctx context.Context, arg AddParticipantParams) error
	CountCommentsByAuthor(ctx context.Context, authorID uuid.UUID) (int64, error)
	CountCommentsInRange(ctx context.Context, arg CountCommentsInRangeParams) (int64, error)
	CountDAUInRange(ctx context.Context, arg CountDAUInRangeParams) ([]CountDAUInRangeRow, error)
	CountDailyActiveUsers(ctx context.Context, visitDate time.Time) (int64, error)
	CountNewUsersInRange(ctx context.Context, arg CountNewUsersInRangeParams) (int64, error)
	CountPosts(ctx context.Context) (int64, error)
	CountPostsByAuthor(ctx context.Context, authorID uuid.UUID) (int64, error)
	CountPostsInRange(ctx context.Context, arg CountPostsInRangeParams) (int64, error)
	CountTopLevelComments(ctx context.Context, postID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateConversation(ctx context.Context) (MessageConversation, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (PushSubscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error)
	DecrementImageRefCount(ctx context.Context, url string) error
	DecrementPostCommentCount(ctx context.Context, id uuid.UUID) error
	DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) error
	DeleteVerificationCodes(ctx context.Context, arg DeleteVerificationCodesParams) error
	FollowUser(ctx context.Context, arg FollowUserParams) error
	GetAdminUsers(ctx context.Context) ([]User, error)
	GetCommentByID(ctx context.Context, id uuid.UUID) (Comment, error)
	GetCommentByIDIncludeDeleted(ctx context.Context, id uuid.UUID) (Comment, error)
	GetConfigValue(ctx context.Context, key string) (string, error)
	GetConversationBetweenUsers(ctx context.Context, arg GetConversationBetweenUsersParams) (MessageConversation, error)
	GetConversationByID(ctx context.Context, id uuid.UUID) (MessageConversation, error)
	GetEmailPref(ctx context.Context, arg GetEmailPrefParams) (EmailPreference, error)
	GetEmailPreferences(ctx context.Context, userID uuid.UUID) ([]EmailPreference, error)
	GetFollowerCount(ctx context.Context, followingID uuid.UUID) (int64, error)
	GetFollowerIDs(ctx context.Context, followingID uuid.UUID) ([]uuid.UUID, error)
	GetFollowers(ctx context.Context, arg GetFollowersParams) ([]User, error)
	GetFollowing(ctx context.Context, arg GetFollowingParams) ([]User, error)
	GetFollowingCount(ctx context.Context, followerID uuid.UUID) (int64, error)
	GetFollowingIDs(ctx context.Context, followerID uuid.UUID) ([]uuid.UUID, error)
	GetImageByURL(ctx context.Context, url string) (Image, error)
	GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error)
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotificationPref(ctx context.Context, arg GetNotificationPrefParams) (NotificationPreference, error)
	GetNotificationPreferences(ctx context.Context, userID uuid.UUID) ([]NotificationPreference, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetOtherParticipantUserID(ctx context.Context, arg GetOtherParticipantUserIDParams) (uuid.UUID, error)
	GetParticipant(ctx context.Context, arg GetParticipantParams) (MessageParticipant, error)
	GetParticipants(ctx context.Context, conversationID uuid.UUID) ([]MessageParticipant, error)
	GetPostByID(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostByIDIncludeDeleted(ctx context.Context, id uuid.UUID) (Post, error)
	GetPostSubscribers(ctx context.Context, postID uuid.UUID) ([]uuid.UUID, error)
	GetPushSubscriptionsByUserID(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error)
	GetSubscribedPostIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	GetTotalUnreadCount(ctx context.Context, userID uuid.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailOrUsername(ctx context.Context, arg GetUserByEmailOrUsernameParams) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error)
	HasUserReadPost(ctx context.Context, arg HasUserReadPostParams) (bool, error)
	IncrementPostCommentCount(ctx context.Context, id uuid.UUID) error
	IncrementPostViews(ctx context.Context, id uuid.UUID) error
	IncrementUnreadCounts(ctx context.Context, arg IncrementUnreadCountsParams) error
	IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error)
	IsSubscribedToPost(ctx context.Context, arg IsSubscribedToPostParams) (bool, error)
	ListCommentsByAuthor(ctx context.Context, arg ListCommentsByAuthorParams) ([]Comment, error)
	ListConfig(ctx context.Context) ([]SiteConfig, error)
	ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]MessageConversation, error)
	ListFeaturedPosts(ctx context.Context, arg ListFeaturedPostsParams) ([]Post, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error)
	ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]Post, error)
	ListRecentPosts(ctx context.Context, arg ListRecentPostsParams) ([]Post, error)
	ListReplies(ctx context.Context, arg ListRepliesParams) ([]Comment, error)
	ListTopLevelComments(ctx context.Context, arg ListTopLevelCommentsParams) ([]Comment, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error
	MarkNotificationReadByID(ctx context.Context, id uuid.UUID) error
	MarkNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkVerificationCodeUsed(ctx context.Context, id uuid.UUID) error
	PinComment(ctx context.Context, id uuid.UUID) error
	PinPost(ctx context.Context, id uuid.UUID) error
	RecordPostRead(ctx context.Context, arg RecordPostReadParams) error
	RecordUserVisit(ctx context.Context, userID uuid.UUID) error
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetPostClosed(ctx context.Context, arg SetPostClosedParams) error
	SetUserBanned(ctx context.Context, arg SetUserBannedParams) error
	SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error
	SetUserRole(ctx context.Context, arg SetUserRoleParams) error
	SetUserVerified(ctx context.Context, id uuid.UUID) error
	SoftDeleteComment(ctx context.Context, id uuid.UUID) error
	SoftDeleteMessage(ctx context.Context, id uuid.UUID) error
	SoftDeletePost(ctx context.Context, id uuid.UUID) error
	SubscribeToPost(ctx context.Context, arg SubscribeToPostParams) error
	UnfollowUser(ctx context.Context, arg UnfollowUserParams) error
	UnpinComment(ctx context.Context, id uuid.UUID) error
	UnpinPost(ctx context.Context, id uuid.UUID) error
	UnsubscribeFromPost(ctx context.Context, arg UnsubscribeFromPostParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateConversationLastMessage(ctx context.Context, id uuid.UUID) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertConfigValue(ctx context.Context, arg UpsertConfigValueParams) error
	UpsertEmailPreference(ctx context.Context, arg UpsertEmailPreferenceParams) error
	UpsertImage(ctx context.Context, url string) (Image, error)
	UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error
}

var _ Querier = (*Queries)(nil)
