// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getPostSubscribers = `-- name: GetPostSubscribers :many
SELECT user_id FROM post_subscriptions WHERE post_id = $1
`

func (q *Queries) GetPostSubscribers(ctx context.Context, postID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getPostSubscribers, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscribedPostIDs = `-- name: GetSubscribedPostIDs :many
SELECT post_id FROM post_subscriptions WHERE user_id = $1
`

func (q *Queries) GetSubscribedPostIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getSubscribedPostIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var post_id uuid.UUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isSubscribedToPost = `-- name: IsSubscribedToPost :one
SELECT EXISTS(
    SELECT 1 FROM post_subscriptions WHERE post_id = $1 AND user_id = $2
)
`

type IsSubscribedToPostParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsSubscribedToPost(ctx context.Context, arg IsSubscribedToPostParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isSubscribedToPost, arg.PostID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const subscribeToPost = `-- name: SubscribeToPost :exec
INSERT INTO post_subscriptions (post_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type SubscribeToPostParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SubscribeToPost(ctx context.Context, arg SubscribeToPostParams) error {
	_, err := q.db.ExecContext(ctx, subscribeToPost, arg.PostID, arg.UserID)
	return err
}

const unsubscribeFromPost = `-- name: UnsubscribeFromPost :exec
DELETE FROM post_subscriptions WHERE post_id = $1 AND user_id = $2
`

type UnsubscribeFromPostParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnsubscribeFromPost(ctx context.Context, arg UnsubscribeFromPostParams) error {
	_, err := q.db.ExecContext(ctx, unsubscribeFromPost, arg.PostID, arg.UserID)
	return err
}
