// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countDAUInRange = `-- name: CountDAUInRange :many
SELECT visit_date, COUNT(DISTINCT user_id) AS count
FROM user_visits
WHERE visit_date >= $1 AND visit_date <= $2
GROUP BY visit_date
ORDER BY visit_date
`

type CountDAUInRangeParams struct {
	VisitDate   time.Time `json:"visit_date"`
	VisitDate_2 time.Time `json:"visit_date_2"`
}

type CountDAUInRangeRow struct {
	VisitDate time.Time `json:"visit_date"`
	Count     int64     `json:"count"`
}

func (q *Queries) CountDAUInRange(ctx context.Context, arg CountDAUInRangeParams) ([]CountDAUInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, countDAUInRange, arg.VisitDate, arg.VisitDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDAUInRangeRow{}
	for rows.Next() {
		var i CountDAUInRangeRow
		if err := rows.Scan(&i.VisitDate, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDailyActiveUsers = `-- name: CountDailyActiveUsers :one
SELECT COUNT(DISTINCT user_id) FROM user_visits WHERE visit_date = $1
`

func (q *Queries) CountDailyActiveUsers(ctx context.Context, visitDate time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDailyActiveUsers, visitDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewUsersInRange = `-- name: CountNewUsersInRange :one
SELECT COUNT(*) FROM users
WHERE created_at >= $1 AND created_at < $2
`

type CountNewUsersInRangeParams struct {
	CreatedAt   time.Time `json:"created_at"`
	CreatedAt_2 time.Time `json:"created_at_2"`
}

func (q *Queries) CountNewUsersInRange(ctx context.Context, arg CountNewUsersInRangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNewUsersInRange, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :exec
INSERT INTO oauth_accounts (user_id, provider, provider_id)
VALUES ($1, $2, $3)
ON CONFLICT (provider, provider_id) DO NOTHING
`

type CreateOAuthAccountParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Provider   string    `json:"provider"`
	ProviderID string    `json:"provider_id"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthAccount, arg.UserID, arg.Provider, arg.ProviderID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, verified, avatar, role)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	Verified     bool           `json:"verified"`
	Avatar       sql.NullString `json:"avatar"`
	Role         UserRole       `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Verified,
		arg.Avatar,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.Avatar,
		&i.Introduction,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO user_subscriptions (follower_id, following_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.ExecContext(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const getAdminUsers = `-- name: GetAdminUsers :many
SELECT id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at FROM users WHERE role = 'ADMIN' ORDER BY created_at
`

func (q *Queries) GetAdminUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Verified,
			&i.Avatar,
			&i.Introduction,
			&i.Role,
			&i.Banned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowerCount = `-- name: GetFollowerCount :one
SELECT COUNT(*) FROM user_subscriptions WHERE following_id = $1
`

func (q *Queries) GetFollowerCount(ctx context.Context, followingID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFollowerCount, followingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowerIDs = `-- name: GetFollowerIDs :many
SELECT follower_id FROM user_subscriptions WHERE following_id = $1
`

func (q *Queries) GetFollowerIDs(ctx context.Context, followingID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getFollowerIDs, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var follower_id uuid.UUID
		if err := rows.Scan(&follower_id); err != nil {
			return nil, err
		}
		items = append(items, follower_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id, u.username, u.email, u.password_hash, u.verified, u.avatar, u.introduction, u.role, u.banned, u.created_at, u.updated_at FROM users u
JOIN user_subscriptions us ON us.follower_id = u.id
WHERE us.following_id = $1
ORDER BY us.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowersParams struct {
	FollowingID uuid.UUID `json:"following_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getFollowers, arg.FollowingID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Verified,
			&i.Avatar,
			&i.Introduction,
			&i.Role,
			&i.Banned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.id, u.username, u.email, u.password_hash, u.verified, u.avatar, u.introduction, u.role, u.banned, u.created_at, u.updated_at FROM users u
JOIN user_subscriptions us ON us.following_id = u.id
WHERE us.follower_id = $1
ORDER BY us.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Verified,
			&i.Avatar,
			&i.Introduction,
			&i.Role,
			&i.Banned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowingCount = `-- name: GetFollowingCount :one
SELECT COUNT(*) FROM user_subscriptions WHERE follower_id = $1
`

func (q *Queries) GetFollowingCount(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFollowingCount, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowingIDs = `-- name: GetFollowingIDs :many
SELECT following_id FROM user_subscriptions WHERE follower_id = $1
`

func (q *Queries) GetFollowingIDs(ctx context.Context, followerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getFollowingIDs, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var following_id uuid.UUID
		if err := rows.Scan(&following_id); err != nil {
			return nil, err
		}
		items = append(items, following_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_id, created_at FROM oauth_accounts WHERE provider = $1 AND provider_id = $2 LIMIT 1
`

type GetOAuthAccountParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRowContext(ctx, getOAuthAccount, arg.Provider, arg.ProviderID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.Avatar,
		&i.Introduction,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at FROM users WHERE email = $1 OR username = $2 LIMIT 1
`

type GetUserByEmailOrUsernameParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, arg GetUserByEmailOrUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailOrUsername, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.Avatar,
		&i.Introduction,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.Avatar,
		&i.Introduction,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.Avatar,
		&i.Introduction,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
    SELECT 1 FROM user_subscriptions WHERE follower_id = $1 AND following_id = $2
)
`

type IsFollowingParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFollowing, arg.FollowerID, arg.FollowingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Verified,
			&i.Avatar,
			&i.Introduction,
			&i.Role,
			&i.Banned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordUserVisit = `-- name: RecordUserVisit :exec
INSERT INTO user_visits (visit_date, user_id)
VALUES (CURRENT_DATE, $1)
ON CONFLICT DO NOTHING
`

func (q *Queries) RecordUserVisit(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, recordUserVisit, userID)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at FROM users
WHERE username ILIKE $1 OR email ILIKE $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Verified,
			&i.Avatar,
			&i.Introduction,
			&i.Role,
			&i.Banned,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserBanned = `-- name: SetUserBanned :exec
UPDATE users SET banned = $2, updated_at = NOW() WHERE id = $1
`

type SetUserBannedParams struct {
	ID     uuid.UUID `json:"id"`
	Banned bool      `json:"banned"`
}

func (q *Queries) SetUserBanned(ctx context.Context, arg SetUserBannedParams) error {
	_, err := q.db.ExecContext(ctx, setUserBanned, arg.ID, arg.Banned)
	return err
}

const setUserPasswordHash = `-- name: SetUserPasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type SetUserPasswordHashParams struct {
	ID           uuid.UUID      `json:"id"`
	PasswordHash sql.NullString `json:"password_hash"`
}

func (q *Queries) SetUserPasswordHash(ctx context.Context, arg SetUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, setUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE users SET role = $2, updated_at = NOW() WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role UserRole  `json:"role"`
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const setUserVerified = `-- name: SetUserVerified :exec
UPDATE users SET verified = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SetUserVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setUserVerified, id)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM user_subscriptions WHERE follower_id = $1 AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.ExecContext(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = COALESCE($2, username),
    email = COALESCE($3, email),
    introduction = COALESCE($4, introduction),
    avatar = COALESCE($5, avatar),
    updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, verified, avatar, introduction, role, banned, created_at, updated_at
`

type UpdateUserParams struct {
	ID           uuid.UUID      `json:"id"`
	Username     sql.NullString `json:"username"`
	Email        sql.NullString `json:"email"`
	Introduction sql.NullString `json:"introduction"`
	Avatar       sql.NullString `json:"avatar"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Introduction,
		arg.Avatar,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Verified,
		&i.Avatar,
		&i.Introduction,
		&i.Role,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
