// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (email, code, type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, email, code, type, expires_at, used, created_at
`

type CreateVerificationCodeParams struct {
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	Type      string    `json:"type"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRowContext(ctx, createVerificationCode,
		arg.Email,
		arg.Code,
		arg.Type,
		arg.ExpiresAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.Type,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVerificationCodes = `-- name: DeleteVerificationCodes :exec
DELETE FROM verification_codes WHERE email = $1 AND type = $2
`

type DeleteVerificationCodesParams struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

func (q *Queries) DeleteVerificationCodes(ctx context.Context, arg DeleteVerificationCodesParams) error {
	_, err := q.db.ExecContext(ctx, deleteVerificationCodes, arg.Email, arg.Type)
	return err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT id, email, code, type, expires_at, used, created_at FROM verification_codes
WHERE email = $1 AND type = $2 AND used = FALSE AND expires_at > NOW()
ORDER BY created_at DESC
LIMIT 1
`

type GetVerificationCodeParams struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

func (q *Queries) GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRowContext(ctx, getVerificationCode, arg.Email, arg.Type)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.Type,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const markVerificationCodeUsed = `-- name: MarkVerificationCodeUsed :exec
UPDATE verification_codes SET used = TRUE WHERE id = $1
`

func (q *Queries) MarkVerificationCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markVerificationCodeUsed, id)
	return err
}
